#pragma once

/// Font Awesome 6 Solid glyph codepoints for use in ImGui labels.
/// These MUST be macros (not constexpr) for string literal concatenation:
///   ImGui::Button(ICON_FA_PLAY " Play");

#define ICON_FA_PLAY           "\xef\x81\x8b"
#define ICON_FA_PAUSE          "\xef\x81\x8c"
#define ICON_FA_STOP           "\xef\x81\x8d"
#define ICON_FA_FORWARD        "\xef\x81\x8e"
#define ICON_FA_BACKWARD       "\xef\x81\x8a"
#define ICON_FA_COG            "\xef\x80\x93"
#define ICON_FA_COGS           "\xef\x82\x85"
#define ICON_FA_EYE            "\xef\x81\xae"
#define ICON_FA_EYE_SLASH      "\xef\x81\xb0"
#define ICON_FA_CUBE           "\xef\x86\xb2"
#define ICON_FA_CUBES          "\xef\x86\xb3"
#define ICON_FA_FOLDER         "\xef\x81\xbb"
#define ICON_FA_FOLDER_OPEN    "\xef\x81\xbc"
#define ICON_FA_FILE           "\xef\x85\x9b"
#define ICON_FA_IMAGE          "\xef\x80\xbe"
#define ICON_FA_CAMERA         "\xef\x80\xb0"
#define ICON_FA_VIDEO          "\xef\x80\xbd"
#define ICON_FA_MUSIC          "\xef\x80\x81"
#define ICON_FA_TERMINAL       "\xef\x84\xa0"
#define ICON_FA_BUG            "\xef\x86\x88"
#define ICON_FA_CHART_LINE     "\xef\x88\x81"
#define ICON_FA_CHART_BAR      "\xef\x82\x80"
#define ICON_FA_SEARCH         "\xef\x80\x82"
#define ICON_FA_TRASH          "\xef\x87\xb8"
#define ICON_FA_UNDO           "\xef\x83\xa2"
#define ICON_FA_REDO           "\xef\x80\x9e"
#define ICON_FA_SAVE           "\xef\x83\x87"
#define ICON_FA_DOWNLOAD       "\xef\x80\x99"
#define ICON_FA_UPLOAD         "\xef\x82\x93"
#define ICON_FA_ARROWS_ROTATE  "\xef\x80\xa1"
#define ICON_FA_XMARK          "\xef\x80\x8d"
#define ICON_FA_CHECK          "\xef\x80\x8c"
#define ICON_FA_INFO_CIRCLE    "\xef\x81\x9a"
#define ICON_FA_WARNING        "\xef\x81\xb1"
#define ICON_FA_CIRCLE_EXCL    "\xef\x81\xaa"
#define ICON_FA_EXPAND         "\xef\x81\xa5"
#define ICON_FA_COMPRESS       "\xef\x81\xa6"
#define ICON_FA_LAYER_GROUP    "\xef\x97\xbd"
#define ICON_FA_BONE           "\xef\x97\x97"
#define ICON_FA_DRAW_POLYGON   "\xef\x97\xae"
#define ICON_FA_VECTOR_SQUARE  "\xef\x97\xab"
#define ICON_FA_LIGHTBULB      "\xef\x83\xab"
#define ICON_FA_PALETTE        "\xef\x94\xbf"
#define ICON_FA_GAUGE_HIGH     "\xef\x98\xa5"
#define ICON_FA_MEMORY         "\xef\x94\xb8"
#define ICON_FA_CROSSHAIRS     "\xef\x81\x9b"
#define ICON_FA_DESKTOP        "\xef\x84\x88"
